### PR TITLE
Apply timeouts on retry again.

### PR DESCRIPTION
**Pull request by elyobo**
This was broken by recent changes.  The timeout is now correctly
applied, the `shouldRetry` option is documented, and the `limit` option
can now be set to a falsy value for indefinite retries (potentially
short circuited by `shouldRetry`.

### CODE REVIEW

**Comment by elyobo** [comment]
Publish minor release? It's a bug fix (missing delay) and a minor feature
change (unlimited retry behaviour).

**Comment by elyobo** [comment]
The security issues might require an upgrade of the dependencies in package.json, not just the lock, as the package.json would still be permitting versions with security problems.

**Comment by elyobo** [comment]
Ah, you did do a minor release, but didn't `npm publish` (which I now have).

**Comment by axdg** [comment]
^^... yeah, it fixed all but one (`braces`).

**Pull request merged**
