### PR TITLE
Async Queue

### PR DESCRIPTION
**Pull request by axdg**
@liam... I'm going to close the PR from the fork and merge this one.

@elyobo... I think I pinged @liam accidentally.

### CODE REVIEW

**Comment by liam** [comment]
@liam doesn't do what you think.

**Comment by elyobo** [comment]
Hahaha, no, indeed it doesn't, was discussing with @axdg already.  Fix and more appropriate tests up in a second.  Nice name btw @liam

**Comment by elyobo** [comment]
Fix included in https://github.com/raywhite/async-hofs/pull/6

**Comment by elyobo** [comment]
Funnily enough I interpreted "@liam doesn't do what you think" as a comment on the PR (which, indeed, doesn't do what I think it did) rather than telling @axdg that he was tagging the wrong person :D

**Pull request merged**
